# Generated by Django 3.2.5 on 2021-07-11 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=7)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=600)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
