# Generated by Django 3.2.4 on 2021-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contact_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='manager',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
